name: unlockme
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1
  drop_shadow_image: ^0.9.1
  flutter_native_splash: ^2.4.1
  percent_indicator: ^4.2.3
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.3.0
  equatable: ^2.0.5
  panara_dialogs: ^0.1.5
  bloc: ^8.1.4
  firebase_database: ^11.1.0
  flutter_local_notifications: ^17.2.2
  firebase_messaging: ^15.1.0
  logger: ^2.4.0
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  badges: ^3.1.2
  shared_preferences: ^2.3.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env